Repository openscope/openscope, pull requests merged in 2018-11, with the labels that each got.

#1156 documentation/1075 - Typo In surgePattern documentation
  CHANGELOG.md
  documentation/spawnPatternMethodReadme.md
Labels: documentation

#1159 bugfix/1147 - Callsigns in tutorial should update when switching airports
  CHANGELOG.md
  src/assets/scripts/client/tutorial/TutorialView.js
Labels: BUGFIX

#1161 enhancement/883 - Light tailwind landings wrongfully causing penalty
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftModel.js
Labels: enhancement

#1111 refactor/1001 - Remove support for WIP airports
  CHANGELOG.md
  assets/airports/airportLoadList.js
  src/assets/scripts/client/UiController.js
  src/assets/scripts/client/airport/AirportController.js
  src/assets/scripts/client/airport/AirportModel.js
  src/assets/scripts/client/constants/gameOptionConstants.js
  src/assets/scripts/client/constants/selectors.js
  src/assets/style/module/airport/_airport.less
  src/templates/_airportSwitch.hbs
  test/airport/_mocks/airportLoadListMocks.js
  test/game/GameOptions.spec.js
Labels: refactor

#1063 bugfix/1045 - Arrivals ignoring altitude restrictions
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftModel.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js
  test/aircraft/AircraftModel.spec.js
  test/aircraft/_mocks/aircraftMocks.js
  test/airport/_mocks/airportJsonMock.js
Labels: BUGFIX

#1172 refactor/1171 - Move tutorial from InputController to UiController
  CHANGELOG.md
  src/assets/scripts/client/AppController.js
  src/assets/scripts/client/InputController.js
  src/assets/scripts/client/ui/TutorialView.js
  src/assets/scripts/client/ui/UiController.js
Labels: refactor

#1167 feature/159 - Add in-game link to github repo
  CHANGELOG.md
  assets/images/GitHub-Mark-Light-32px.png
  assets/images/GitHub_Logo_White.png
  src/assets/style/module/controls/_controls.less
  src/templates/_footer.hbs
Labels: feature

#1117 documentation/1115 - Fix broken documentation links
  CHANGELOG.md
  README.md
  documentation/aircraft-format.md
  documentation/aircraft-separation.md
  documentation/airline-format.md
  documentation/airport-file-standards.md
  documentation/airport-format.md
  documentation/development-processes-checklists.md
  documentation/git-flow-process.md
  documentation/spawnPatternMethodReadme.md
  documentation/spawnPatternReadme.md
Labels: documentation

#1164 refactor/308 - abstract Aircraft.getWind() to the AirportModel
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftModel.js
  src/assets/scripts/client/airport/AirportModel.js
Labels: refactor

#1155 bugfix/155 - Accept entrail property in spawnPatternModel
  CHANGELOG.md
  src/assets/scripts/client/trafficGenerator/SpawnPatternModel.js
Labels: BUGFIX

#1196 bugfix/1193
  CHANGELOG.md
  src/assets/scripts/client/ui/UiController.js
Labels: BUGFIX

#1203 bugfix/1202
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/aircraft/Pilot/Pilot.js
Labels: BUGFIX

#1214 refactor/1208 - Update TCX callsign
  CHANGELOG.md
  assets/airlines/tcx.json
Labels: airport work, refactor

#1215 refactor/1209
  CHANGELOG.md
  assets/airlines/tom.json
Labels: airport work, refactor

#1213 feature/1212 - Create aircraft specific pilot voice for read backs
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/aircraft/AircraftController.js
  src/assets/scripts/client/aircraft/AircraftModel.js
  src/assets/scripts/client/constants/speechConstants.js
  src/assets/scripts/client/speech.js
Labels: feature

#1185 enhancement/604 - Add timeshare to data block
  .gitignore
  CHANGELOG.md
  src/assets/scripts/client/AppController.js
  src/assets/scripts/client/aircraft/AircraftTypeDefinitionModel.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/RouteModel.js
  src/assets/scripts/client/airport/AirportModel.js
  src/assets/scripts/client/canvas/CanvasController.js
  src/assets/scripts/client/constants/themes/classic/modules/dataBlock.js
  src/assets/scripts/client/constants/themes/default/modules/dataBlock.js
  src/assets/scripts/client/engine/TimeKeeper.js
  src/assets/scripts/client/scope/RadarTargetModel.js
  test/aircraft/AircraftTypeDefinitionModel.spec.js
  test/aircraft/FlightManagementSystem/RouteModel.spec.js
  test/scope/RadarTargetModel.spec.js
Labels: enhancement

#1201 devops/1197 - Expand analytics and event tracking
  CHANGELOG.md
  README.md
  documentation/event-tracking.md
  src/assets/scripts/client/AppController.js
  src/assets/scripts/client/EventTracker.js
  src/assets/scripts/client/InputController.js
  src/assets/scripts/client/constants/selectors.js
  src/assets/scripts/client/constants/trackableEvents.js
  src/assets/scripts/client/game/GameController.js
  src/assets/scripts/client/game/GameOptions.js
  src/assets/scripts/client/speech.js
  src/assets/scripts/client/ui/TutorialView.js
  src/assets/scripts/client/ui/UiController.js
  src/templates/_footer.hbs
  src/templates/layout.hbs
Labels: devops

#1229 enhancement/678 - removes wind vane from `CanvasController`
  CHANGELOG.md
  src/assets/scripts/client/canvas/CanvasController.js
Labels: enhancement

#1237 bugfix/1154 - Ensure that the runway is valid for SID before takeoff
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/aircraft/AircraftModel.js
  src/assets/scripts/client/aircraft/Pilot/Pilot.js
  test/aircraft/AircraftModel.spec.js
  test/aircraft/Pilot/Pilot.spec.js
Labels: BUGFIX

#1002 bugfix/955 - Overhaul `sid` command
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/RouteModel.js
  src/assets/scripts/client/aircraft/Pilot/Pilot.js
  src/assets/scripts/client/navigationLibrary/ProcedureModel.js
  test/aircraft/FlightManagementSystem/Fms.spec.js
  test/aircraft/FlightManagementSystem/RouteModel.spec.js
Labels: BUGFIX

#1143 devops/1137 - Update project dependencies
  .babelrc
  .npmrc
  .nvmrc
  .travis.yml
  CHANGELOG.md
  Gulpfile.js
  package-lock.json
  package.json
  src/assets/scripts/client/index.js
  src/assets/scripts/server/index.js
  tools/options.js
  tools/tasks/buildMarkup.js
  tools/tasks/jsonAssembler.js
  tools/tasks/mediaTasks.js
  tools/tasks/scriptTasks.js
  tools/tasks/styleTasks.js
  tools/tasks/utilityTasks.js
Labels: devops
