Repository openscope/openscope, pull requests merged in 2018-10, with the labels that each got.

#1102 bugfix/1101
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftModel.js
Labels: BUGFIX

#1100 bugfix/1099 - Change B747 to B744 in THY.json
  CHANGELOG.md
  assets/airlines/thy.json
Labels: BUGFIX

#1109 refactor/1108 - Overhaul of KLAS
  CHANGELOG.md
  assets/airlines/aay.json
  assets/airlines/amx.json
  assets/airlines/asa.json
  assets/airlines/cfg.json
  assets/airlines/edw.json
  assets/airlines/tcx.json
  assets/airports/airportLoadList.js
  assets/airports/klas.json
  package-lock.json
Labels: airport work, refactor

#1037 feature/1033 - overflights
  CHANGELOG.md
  documentation/airport-format.md
  documentation/spawnPatternReadme.md
  src/assets/scripts/client/aircraft/AircraftModel.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js
  src/assets/scripts/client/aircraft/StripView/StripViewModel.js
  src/assets/scripts/client/airport/AirportModel.js
  src/assets/scripts/client/constants/aircraftConstants.js
  src/assets/scripts/client/constants/selectors.js
  src/assets/scripts/client/trafficGenerator/SpawnPatternModel.js
  src/assets/style/helpers/_vars.less
  src/assets/style/landmark/_stripView.less
  src/templates/_stripView.hbs
  test/aircraft/FlightManagementSystem/Fms.spec.js
  test/aircraft/Pilot/Pilot.spec.js
  test/aircraft/_mocks/aircraftMocks.js
  test/trafficGenerator/SpawnPatternModel.spec.js
Labels: feature

#1126 enhancement/1123 - Make runway mandatory in "taxi" command
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftCommander.js
  test/aircraft/AircraftModel.spec.js
Labels: enhancement

#1140 documentation/1138 - Remove contributors block from package.json
  CHANGELOG.md
  package.json
Labels: documentation

#1129 feature/793 - Add `airac` command and property to airports
  CHANGELOG.md
  assets/airports/cyow.json
  assets/airports/eddm.json
  assets/airports/kabq.json
  assets/airports/kbos.json
  assets/airports/kdtw.json
  assets/airports/kpdx.json
  assets/airports/ksea.json
  assets/airports/kstl.json
  assets/airports/rjtt.json
  documentation/airport-format.md
  src/assets/scripts/client/InputController.js
  src/assets/scripts/client/airport/AirportController.js
  src/assets/scripts/client/airport/AirportModel.js
  src/assets/scripts/client/constants/inputConstants.js
  src/assets/scripts/client/parsers/aircraftCommandParser/aircraftCommandDefinitions.js
  src/assets/scripts/client/parsers/aircraftCommandParser/aircraftCommandMap.js
  test/airport/_mocks/airportJsonMock.js
Labels: feature

#1106 bugfix/1104 - Fix flight strip console warning
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftController.js
Labels: BUGFIX

#1127 refactor/1144 - moved calculateSpawnHeading
  CHANGELOG.md
  src/assets/scripts/client/aircraft/FlightManagementSystem/RouteModel.js
  src/assets/scripts/client/trafficGenerator/SpawnPatternModel.js
  test/aircraft/FlightManagementSystem/RouteModel.spec.js
  test/trafficGenerator/SpawnPatternModel.spec.js
Labels: refactor

#1142 documentation/1141 - Update documentation for taxi command
  CHANGELOG.md
  documentation/aircraft-commands.md
Labels: documentation

#1122 bugfix/1103 - Fix pressing ESC doesn't fully clear the command bar
  CHANGELOG.md
  src/assets/scripts/client/InputController.js
Labels: BUGFIX

#970 enhancement/966 - Improve terrain generation documentation
  CHANGELOG.md
  documentation/airport-terrain-generation.md
Labels: WIP, enhancement

#1131 feature/1017 - Add more GA aircraft
  CHANGELOG.md
  assets/aircraft/aa1.json
  assets/aircraft/aa5.json
  assets/aircraft/c150.json
  assets/aircraft/hdjt.json
  assets/airlines/n.json
Labels: feature

#1150 bugfix/1149 - Ensure all flight strips are removed when switching to another airport
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftController.js
Labels: BUGFIX

#1134 refactor/1133 - Improve InputController class
  CHANGELOG.md
  src/assets/scripts/client/InputController.js
Labels: WIP, refactor

#1153 bugfix/1152 - Fix GameClockView crashes sim in Firefox
  CHANGELOG.md
  src/assets/scripts/client/InputController.js
Labels: BUGFIX
