Repository openscope/openscope, pull requests merged in 2018-05, with the labels that each got.

#951 hotfix/950
  CHANGELOG.md
  package.json
  src/assets/scripts/client/parsers/aircraftCommandParser/aircraftCommandMap.js
Labels: HOTFIX

#957 documentation/956
  CHANGELOG.md
  documentation/aircraft-commands.md
Labels: documentation

#930 refactor/782
  CHANGELOG.md
  assets/airports/airportLoadList.js
  assets/airports/katl.json
  assets/airports/terrain/katl.geojson
  documentation/airport-guides/katl.md
Labels: airport work, refactor

#971 bugfix/968
  CHANGELOG.md
  assets/airlines/n.json
Labels: BUGFIX

#897 refactor/874
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftModel.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/RouteModel.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/WaypointModel.js
  src/assets/scripts/client/aircraft/Pilot/Pilot.js
  src/assets/scripts/client/constants/waypointConstants.js
  src/assets/scripts/client/utilities/navigationUtilities.js
  test/aircraft/AircraftModel.spec.js
  test/aircraft/FlightManagementSystem/Fms.spec.js
  test/aircraft/FlightManagementSystem/RouteModel.spec.js
  test/aircraft/FlightManagementSystem/WaypointModel.spec.js
  test/aircraft/Pilot/Pilot.spec.js
  test/aircraft/Pilot/_baseSpec.tmp
  test/aircraft/Pilot/applyArrivalProcedure.spec.js
  test/aircraft/Pilot/applyDepartureProcedure.spec.js
  test/aircraft/Pilot/applyNewRoute.spec.js
  test/aircraft/Pilot/applyPartialRouteAmendment.spec.js
  test/aircraft/Pilot/cancelApproachClearance.spec.js
  test/aircraft/Pilot/clearedAsFiled.spec.js
  test/aircraft/Pilot/climbViaSid.spec.js
  test/aircraft/Pilot/conductInstrumentApproach.spec.js
  test/aircraft/Pilot/descendViaStar.spec.js
  test/aircraft/Pilot/goAround.spec.js
  test/aircraft/Pilot/initiateHoldingPattern.spec.js
  test/aircraft/Pilot/maintainAltitude.spec.js
  test/aircraft/Pilot/maintainHeading.spec.js
  test/aircraft/Pilot/maintainPresentHeading.spec.js
  test/aircraft/Pilot/maintainSpeed.spec.js
  test/aircraft/Pilot/proceedDirect.spec.js
  test/aircraft/Pilot/sayTargetHeading.spec.js
  test/aircraft/Pilot/taxiToRunway.spec.js
  test/airport/_mocks/airportJsonMock.js
  test/utilities/navigationUtilities.spec.js
Labels: refactor
