Repository openscope/openscope, pull requests merged in 2018-06, with the labels that each got.

#984 refactor/982
  .gitkeep
  CHANGELOG.md
Labels: refactor

#894 feature/893
  .travis.yml
  CHANGELOG.md
  assets/airlines/afr.json
  assets/airlines/baw.json
  assets/airlines/fin.json
  assets/airlines/ice.json
  assets/airlines/oma.json
  assets/airlines/swr.json
  assets/airlines/tha.json
  assets/airlines/tvs.json
  assets/airports/airportLoadList.js
  assets/airports/lkpr.json
  assets/airports/terrain/lkpr.geojson
  documentation/airport-guides/lkpr.md
Labels: airport work, feature

#980 enhancement/444
  CHANGELOG.md
  assets/images/icons/map.png
  assets/images/icons/stars.png
  src/assets/scripts/client/UiController.js
  src/assets/scripts/client/canvas/CanvasController.js
  src/assets/scripts/client/constants/eventNames.js
  src/assets/scripts/client/constants/selectors.js
  src/templates/_footer.hbs
Labels: feature

#979 bugfix/907
  CHANGELOG.md
  src/assets/scripts/client/trafficGenerator/SpawnPatternModel.js
  test/trafficGenerator/SpawnPatternModel.spec.js
  test/trafficGenerator/_mocks/spawnPatternMocks.js
Labels: BUGFIX

#975 refactor/916
  CHANGELOG.md
  src/assets/scripts/client/AppController.js
  src/assets/scripts/client/InputController.js
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/aircraft/AircraftController.js
  src/assets/scripts/client/aircraft/AircraftModel.js
  src/assets/scripts/client/aircraft/AircraftTypeDefinitionModel.js
  src/assets/scripts/client/aircraft/StripView/StripViewController.js
  src/assets/scripts/client/canvas/CanvasController.js
Labels: refactor

#275 feature/272
  CHANGELOG.md
  assets/airlines/abx.json
  assets/airlines/cks.json
  assets/airports/airportLoadList.js
  assets/airports/kcvg.json
  assets/airports/terrain/kcvg.geojson
  documentation/airport-guides/airport-guide-directory.md
  documentation/airport-guides/kcvg.md
Labels: airport work, feature

#1010 bugfix/1008
  CHANGELOG.md
  assets/airlines/abq.json
  assets/airlines/abw.json
  assets/airlines/aur.json
  assets/airlines/box.json
  assets/airlines/bru.json
  assets/airlines/cao.json
  assets/airlines/fcb.json
  assets/airlines/mgx.json
  assets/airlines/msr.json
  assets/airlines/nmb.json
  assets/airlines/pti.json
Labels: BUGFIX

#1007 enhancement/94
  CHANGELOG.md
  documentation/airport-format.md
  package-lock.json
  package.json
Labels: enhancement
