Repository openscope/openscope, pull requests merged in 2018-08, with the labels that each got.

#1058 bugfix/1044 - Prevent aircraft from deviating off centerline on short final
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftModel.js
Labels: BUGFIX

#1059 bugfix/1047 - fixed Flight number 5000 pronounced incorrectly
  CHANGELOG.md
  src/assets/scripts/client/utilities/radioUtilities.js
  test/utilities/radioUtilities/groupNumbers.spec.js
Labels: BUGFIX

#1066 bugfix/724 - fix settings modal doesn't add active class to control icon
  CHANGELOG.md
  src/assets/scripts/client/UiController.js
Labels: BUGFIX

#1069 bugfix/421 - added 'variation' to spawnPatternModelJsonValidator
  CHANGELOG.md
  src/assets/scripts/client/trafficGenerator/spawnPatternModelJsonValidator.js
Labels: BUGFIX

#1065 bugfix/836 - fix hold in STAR procedure isn't working
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftModel.js
Labels: BUGFIX

#1060 enhancement/1053 - added altitude argument for climb-via and descend-via commands
  CHANGELOG.md
  documentation/aircraft-commands.md
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/aircraft/Pilot/Pilot.js
  src/assets/scripts/client/parsers/aircraftCommandParser/aircraftCommandDefinitions.js
  src/assets/scripts/client/parsers/aircraftCommandParser/argumentParsers.js
  src/assets/scripts/client/parsers/aircraftCommandParser/argumentValidators.js
  test/aircraft/Pilot/Pilot.spec.js
  test/parsers/aircraftCommandParser/argumentParser.spec.js
  test/parsers/aircraftCommandParser/argumentValidator.spec.js
Labels: enhancement

#336 feature/206
  CHANGELOG.md
  assets/airports/airportLoadList.js
  assets/airports/lrop.json
  assets/airports/terrain/lrop.geojson
  documentation/airport-guides/airport-guide-directory.md
  documentation/airport-guides/lrop.md
Labels: airport work, feature
