Repository openscope/openscope, pull requests merged in 2018-09, with the labels that each got.

#1078 feature/1077 - Update flight strips view with Arrivals and Departures lists
  CHANGELOG.md
  src/assets/scripts/client/aircraft/StripView/StripViewController.js
  src/assets/scripts/client/aircraft/StripView/StripViewModel.js
  src/assets/scripts/client/constants/selectors.js
  src/assets/style/landmark/_stripView.less
  src/templates/_stripView.hbs
Labels: feature

#1076 documentation/1074
  CHANGELOG.md
  documentation/scoring.md
Labels: documentation

#1091 bugfix/1086 - P28A climb rate
  CHANGELOG.md
  assets/aircraft/p28a.json
Labels: BUGFIX

#1038 bugfix/1034 - fix waypoint time-to-turn calculations
  CHANGELOG.md
  assets/airports/othh.json
  src/assets/scripts/client/aircraft/AircraftModel.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js
  src/assets/scripts/client/math/flightMath.js
  test/math/flightMath.spec.js
Labels: BUGFIX

#1068 enhancement/111 - draw STARs on canvas
  CHANGELOG.md
  src/assets/scripts/client/canvas/CanvasController.js
  src/assets/scripts/client/constants/themes/classic/modules/scope.js
  src/assets/scripts/client/constants/themes/default/modules/scope.js
  src/assets/scripts/client/navigationLibrary/NavigationLibrary.js
  src/templates/_footer.hbs
Labels: enhancement

#872 bugfix/870 - A/C appear to stop taxiing after one was told to change runways
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/aircraft/AircraftConflict.js
  src/assets/scripts/client/aircraft/AircraftModel.js
  src/assets/scripts/client/aircraft/Pilot/Pilot.js
  test/aircraft/AircraftModel.spec.js
  test/aircraft/Pilot/Pilot.spec.js
Labels: BUGFIX
