Repository openscope/openscope, pull requests merged in 2018-12, with the labels that each got.

#1251 devops/1250 - fixes error code 128 when running npm install
  CHANGELOG.md
  package.json
Labels: devops

#1257 bugfix/1240 - Fix readback from departures in runway queue is not correct
  CHANGELOG.md
  package-lock.json
  src/assets/scripts/client/AppController.js
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/aircraft/AircraftController.js
Labels: BUGFIX

#1267 Fixes flip-flopped A380 speed definitions
  CHANGELOG.md
  assets/aircraft/a388.json
Labels: BUGFIX

#1270 devops/1269 - Connect new google analytics
  CHANGELOG.md
  src/assets/scripts/client/EventTracker.js
  src/templates/layout.hbs
Labels: devops

#1188 refactor/727 - Update the tutorial
  CHANGELOG.md
  src/assets/scripts/client/ui/TutorialStep.js
  src/assets/scripts/client/ui/TutorialView.js
  src/assets/style/landmark/_tutorial.less
Labels: refactor

#1243 enhancement/1238 - route and reroute should include IFR clearance
  CHANGELOG.md
  src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js
  src/assets/scripts/client/aircraft/Pilot/Pilot.js
  test/aircraft/Pilot/Pilot.spec.js
Labels: enhancement

#1248 enhancement/1232 - Distance based sep for same-rwy departures
  CHANGELOG.md
  src/assets/scripts/client/AppController.js
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/aircraft/AircraftController.js
  src/assets/scripts/client/aircraft/AircraftModel.js
  src/assets/scripts/client/aircraft/AircraftTypeDefinitionModel.js
  src/assets/scripts/client/airport/runway/RunwayModel.js
  src/assets/scripts/client/constants/airportConstants.js
  src/assets/scripts/client/constants/eventNames.js
  src/assets/scripts/client/game/GameController.js
  src/assets/scripts/client/game/ScoreController.js
  src/assets/scripts/client/lib/EventBus.js
  src/assets/scripts/client/parsers/aircraftCommandParser/AircraftCommandParser.js
  src/assets/scripts/client/utilities/unitConverters.js
  test/aircraft/AircraftModel.spec.js
  test/aircraft/AircraftTypeDefinitionModel.spec.js
  test/game/ScoreController.spec.js
Labels: enhancement

#1274 bugfix/1158 - fixes Firefox strip bay scrollbars not working
  CHANGELOG.md
  src/assets/scripts/client/AppController.js
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/aircraft/StripView/StripViewController.js
  src/assets/style/landmark/_stripView.less
Labels: BUGFIX

#1277 enhancement/1275
  CHANGELOG.md
  src/templates/layout.hbs
  tools/tasks/buildMarkup.js
Labels: enhancement

#1278 bugfix/1242 - fixes Too-low glidelope intercept messages not showing
  CHANGELOG.md
  src/assets/scripts/client/airport/runway/RunwayModel.js
  test/aircraft/Pilot/Pilot.spec.js
  test/airport/runway/RunwayModel.spec.js
Labels: BUGFIX
