Repository openscope/openscope, pull requests merged in 2018-07, with the labels that each got.

#1006 refactor/1005
  CHANGELOG.md
  assets/airports/krdu.json
Labels: airport work, refactor

#1019 bugfix/1018
  CHANGELOG.md
  assets/airports/ksea.json
Labels: BUGFIX, airport work

#1027 bugfix/915
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftConflict.js
Labels: BUGFIX

#1024 refactor/1023
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  documentation/airport-file-standards.md
  documentation/airport-guides/cyhz.md
  documentation/airport-guides/cyow.md
  documentation/airport-guides/eddf.md
  documentation/airport-guides/eddh.md
  documentation/airport-guides/egcc.md
  documentation/airport-guides/eggw.md
  documentation/airport-guides/egnm.md
  documentation/airport-guides/engm.md
  documentation/airport-guides/kabq.md
  documentation/airport-guides/katl.md
  documentation/airport-guides/kbos.md
  documentation/airport-guides/kcvg.md
  documentation/airport-guides/kdca.md
  documentation/airport-guides/kdtw.md
  documentation/airport-guides/klas.md
  documentation/airport-guides/kmci.md
  documentation/airport-guides/kpdx.md
  documentation/airport-guides/kpit.md
  documentation/airport-guides/krdu.md
  documentation/airport-guides/ksea.md
  documentation/airport-guides/kstl.md
  documentation/airport-guides/lszh.md
  documentation/airport-guides/omaa.md
  documentation/airport-guides/omdb.md
  documentation/airport-guides/othh.md
  documentation/development-processes-checklists.md
  package-lock.json
  package.json
  src/assets/scripts/client/tutorial/TutorialView.js
  src/templates/_loadingView.hbs
  src/templates/layout.hbs
Labels: refactor

#1035 enhancement/949
  CHANGELOG.md
  src/assets/scripts/client/canvas/CanvasController.js
Labels: enhancement

#1016 bugfix/38
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftModel.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/LegModel.js
  src/assets/scripts/client/airport/AirportController.js
  src/assets/scripts/client/airport/runway/RunwayModel.js
  src/assets/scripts/client/canvas/CanvasController.js
  src/assets/scripts/client/constants/aircraftConstants.js
  src/assets/scripts/client/constants/eventNames.js
  src/assets/scripts/client/game/GameController.js
  src/assets/scripts/client/navigationLibrary/FixCollection.js
  src/assets/scripts/client/navigationLibrary/NavigationLibrary.js
  src/assets/scripts/client/navigationLibrary/ProcedureModel.js
  src/assets/scripts/client/parsers/aircraftCommandParser/argumentParsers.js
  src/assets/scripts/client/trafficGenerator/spawnPatternModelJsonValidator.js
  src/assets/scripts/client/utilities/generalUtilities.js
  test/aircraft/AircraftModel.spec.js
  test/aircraft/FlightManagementSystem/LegModel.spec.js
  test/aircraft/FlightManagementSystem/WaypointModel.spec.js
  test/aircraft/Pilot/Pilot.spec.js
  test/aircraft/_mocks/aircraftMocks.js
  test/airport/runway/RunwayModel.spec.js
  test/base/_mocks/positionMocks.js
  test/fixtures/airportFixtures.js
  test/navigationLibrary/Fix/FixCollection.spec.js
  test/navigationLibrary/Procedure/ProcedureModel.spec.js
Labels: BUGFIX

#1031 bugfix/1030
  CHANGELOG.md
  src/assets/style/module/optionDialog/_optionDialog.less
Labels: BUGFIX
