Repository openscope/openscope, pull requests merged in 2019-02, with the labels that each got.

#1310 bugfix/1309 - fixes GameController.game_interval calls continuously after it fires initially
  CHANGELOG.md
  src/assets/scripts/client/engine/TimeKeeper.js
  src/assets/scripts/client/game/GameController.js
  src/assets/scripts/client/trafficGenerator/SpawnPatternModel.js
Labels: BUGFIX, documentation

#1160 feature/898 - Add command to exit holding pattern
  CHANGELOG.md
  documentation/aircraft-commands.md
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js
  src/assets/scripts/client/aircraft/Pilot/Pilot.js
  src/assets/scripts/client/parsers/aircraftCommandParser/aircraftCommandDefinitions.js
  src/assets/scripts/client/parsers/aircraftCommandParser/aircraftCommandMap.js
  test/aircraft/FlightManagementSystem/Fms.spec.js
  test/aircraft/Pilot/Pilot.spec.js
Labels: feature

#1306 bugfix/1305 - fixes range rings center is undefined
  CHANGELOG.md
  src/assets/scripts/client/airport/AirportModel.js
  src/assets/scripts/client/navigationLibrary/FixCollection.js
  test/airport/AirportModel.spec.js
Labels: BUGFIX

#1302 feature/1272 - add version to settings menu
  CHANGELOG.md
  src/assets/scripts/client/ui/SettingsController.js
  src/assets/style/helpers/_vars.less
  src/assets/style/module/optionDialog/_optionDialog.less
Labels: feature

#1315 bugfix/1312 - Fix KRDU arrivals not descending in time
  CHANGELOG.md
  assets/aircraft/hdjt.json
  assets/airlines/n.json
  assets/airports/krdu.json
Labels: BUGFIX
