Repository openscope/openscope, pull requests merged in 2019-11, with the labels that each got.

#1198 feature/1105 - Show airport guide in game
  CHANGELOG.md
  Gulpfile.js
  assets/images/icons/airport-guide.png
  assets/images/icons/airport-guide.svg
  documentation/airport-guides/cyhz.md
  documentation/airport-guides/egcc.md
  documentation/airport-guides/ksea.md
  documentation/airport-guides/not_found.md
  package-lock.json
  src/assets/scripts/client/App.js
  src/assets/scripts/client/AppController.js
  src/assets/scripts/client/EventTracker.js
  src/assets/scripts/client/airportGuide/AirportGuideView.js
  src/assets/scripts/client/airportGuide/AirportGuideViewController.js
  src/assets/scripts/client/changelog/ChangelogController.js
  src/assets/scripts/client/constants/eventNames.js
  src/assets/scripts/client/constants/selectors.js
  src/assets/scripts/client/game/GameController.js
  src/assets/scripts/client/ui/TutorialView.js
  src/assets/scripts/client/ui/UiController.js
  src/assets/style/base/font.less
  src/assets/style/helpers/_vars.less
  src/assets/style/main.less
  src/assets/style/module/airportGuide/_airportGuide.less
  src/assets/style/module/changelog/_changelog.less
  src/index.hbs
  src/templates/_airportGuide.hbs
  src/templates/_changelog.hbs
  src/templates/_footer.hbs
  tools/options.js
  tools/tasks/markdownAssembler.js
  tools/tasks/utilityTasks.js
Labels: feature

#1470 bugfix/1456 - Only allow headings between 001 and 360 degrees
  CHANGELOG.md
  src/assets/scripts/client/parsers/aircraftCommandParser/aircraftCommandParserMessages.js
  src/assets/scripts/client/parsers/aircraftCommandParser/argumentValidators.js
  test/parsers/aircraftCommandParser/argumentValidator.spec.js
Labels: BUGFIX

#1468 feature/1191 - Consolidate command bar buttons
  CHANGELOG.md
  assets/images/icons/questionmark.png
  assets/images/icons/questionmark.svg
  assets/images/icons/scope.png
  assets/images/icons/scope.svg
  src/assets/style/helpers/_vars.less
  src/assets/style/module/controls/_controls.less
  src/assets/style/module/score/_score.less
  src/templates/_footer.hbs
Labels: feature

#1466 feature/45 - Implement *T tool
  CHANGELOG.md
  src/assets/scripts/client/InputController.js
  src/assets/scripts/client/aircraft/AircraftController.js
  src/assets/scripts/client/canvas/CanvasController.js
  src/assets/scripts/client/constants/eventNames.js
  src/assets/scripts/client/constants/gameOptionConstants.js
  src/assets/scripts/client/constants/inputConstants.js
  src/assets/scripts/client/constants/themes/classic/modules/scope.js
  src/assets/scripts/client/constants/themes/default/modules/scope.js
  src/assets/scripts/client/measurement/MeasureLegModel.js
  src/assets/scripts/client/measurement/MeasurePath.js
  src/assets/scripts/client/measurement/MeasureTool.js
  src/assets/scripts/client/navigationLibrary/FixCollection.js
  src/assets/scripts/client/navigationLibrary/FixModel.js
  test/game/GameOptions.spec.js
  test/measurement/MeasureTool.spec.js
  test/navigationLibrary/Fix/FixCollection.spec.js
  test/navigationLibrary/Fix/FixModel.spec.js
Labels: feature

#1475 bugfix/1474 - KAUS crashing from missing FDX fleet
  CHANGELOG.md
  assets/airports/kaus.json
Labels: BUGFIX, airport work

#1477 bugfix/1476 - KSTL terrain not showing
  CHANGELOG.md
  assets/airports/kstl.json
Labels: BUGFIX, airport work

#1444 Enhancement/1431 - Add support for hold parameters for fixes
  CHANGELOG.md
  assets/airports/eggw.json
  assets/airports/einn.json
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/LegModel.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/RouteModel.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/WaypointModel.js
  src/assets/scripts/client/aircraft/Pilot/Pilot.js
  src/assets/scripts/client/constants/globalConstants.js
  src/assets/scripts/client/constants/waypointConstants.js
  src/assets/scripts/client/navigationLibrary/HoldCollection.js
  src/assets/scripts/client/navigationLibrary/HoldModel.js
  src/assets/scripts/client/navigationLibrary/NavigationLibrary.js
  src/assets/scripts/client/navigationLibrary/ProcedureModel.js
  src/assets/scripts/client/parsers/aircraftCommandParser/argumentParsers.js
  src/assets/scripts/client/utilities/navigationUtilities.js
  test/aircraft/FlightManagementSystem/Fms.spec.js
  test/aircraft/FlightManagementSystem/LegModel.spec.js
  test/aircraft/FlightManagementSystem/RouteModel.spec.js
  test/aircraft/FlightManagementSystem/WaypointModel.spec.js
  test/aircraft/FlightManagementSystem/mocks/holdMocks.js
  test/airport/_mocks/airportJsonMock.js
  test/navigationLibrary/HoldCollection.spec.js
  test/navigationLibrary/HoldModel.spec.js
  test/navigationLibrary/NavigationLibrary.spec.js
  test/navigationLibrary/_mocks/holdCollectionMocks.js
  test/navigationLibrary/_mocks/holdModelMocks.js
  test/parsers/aircraftCommandParser/AircraftCommandParser.spec.js
  test/parsers/aircraftCommandParser/argumentParser.spec.js
  test/utilities/navigationUtilities.spec.js
Labels: airport work, enhancement

#1449 enhancement/1402 - Prevent assignment of reserved or nondiscrete beacon codes
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftController.js
  src/assets/scripts/client/utilities/transponderUtilities.js
  test/utilities/transponderUtilities.spec.js
Labels: enhancement

#1473 enhancement/1472 - Update airport terrain files to contain water polygons
  CHANGELOG.md
  assets/airports/terrain/cyhz.geojson
  assets/airports/terrain/cyow.geojson
  assets/airports/terrain/eddf.geojson
  assets/airports/terrain/eddh.geojson
  assets/airports/terrain/eddl.geojson
  assets/airports/terrain/egcc.geojson
  assets/airports/terrain/eggw.geojson
  assets/airports/terrain/einn.geojson
  assets/airports/terrain/katl.geojson
  assets/airports/terrain/kbos.geojson
  assets/airports/terrain/kdca.geojson
  assets/airports/terrain/klas.geojson
  assets/airports/terrain/kmci.geojson
  assets/airports/terrain/kmia.geojson
  assets/airports/terrain/kpdx.geojson
  assets/airports/terrain/ksea.geojson
  assets/airports/terrain/ksfo.geojson
  assets/airports/terrain/kstl.geojson
  assets/airports/terrain/lkpr.geojson
  assets/airports/terrain/lszh.geojson
  assets/airports/terrain/ltba.geojson
  assets/airports/terrain/omaa.geojson
  assets/airports/terrain/omdb.geojson
  assets/airports/terrain/othh.geojson
  documentation/airport-terrain-generation.md
Labels: airport work, enhancement
