Repository openscope/openscope, pull requests merged in 2019-10, with the labels that each got.

#1450 bugfix/1448 - Lower KSFO arrival spawn altitudes
  CHANGELOG.md
  assets/airports/ksfo.json
Labels: BUGFIX, airport work

#1447 bugfix/1446 - Normalise aircraft heading in "say heading" read-back
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftCommander.js
  test/aircraft/AircraftCommander.spec.js
  test/aircraft/_mocks/aircraftCommanderMocks.js
Labels: BUGFIX

#1464 hotfix/1463 - Fix travis build notifications
  .travis.yml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: HOTFIX

#1454 hotfix/1453 - Fix EINN maps property and update terrain
  CHANGELOG.md
  assets/airports/einn.json
  assets/airports/terrain/einn.geojson
  package-lock.json
  package.json
Labels: HOTFIX, airport work

#1452 enhancement/1451 - Add ability to specify the radial for a hold
  CHANGELOG.md
  documentation/aircraft-commands.md
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/aircraft/Pilot/Pilot.js
  src/assets/scripts/client/constants/globalConstants.js
  src/assets/scripts/client/parsers/aircraftCommandParser/aircraftCommandParserMessages.js
  src/assets/scripts/client/parsers/aircraftCommandParser/argumentParsers.js
  src/assets/scripts/client/parsers/aircraftCommandParser/argumentValidators.js
  test/aircraft/Pilot/Pilot.spec.js
  test/parsers/aircraftCommandParser/argumentParser.spec.js
  test/parsers/aircraftCommandParser/argumentValidator.spec.js
Labels: enhancement

#1459 enhancement/1458 - handle distance based holds
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftModel.js
Labels: enhancement
