Repository openscope/openscope, pull requests merged in 2019-03, with the labels that each got.

#1331 bugfix/1329 - Free up CIDs after use
  CHANGELOG.md
  src/assets/scripts/client/aircraft/StripView/StripViewModel.js
Labels: BUGFIX

#1332 bugfix/1324 - Add support for numpad enter
  CHANGELOG.md
  src/assets/scripts/client/InputController.js
  src/assets/scripts/client/constants/inputConstants.js
Labels: BUGFIX

#1336 bugfix/1335 - fix inconsistent state of control buttons due to window onblur / onfocus
  CHANGELOG.md
  src/assets/scripts/client/game/GameController.js
Labels: BUGFIX

#1180 enhancement/10 - Command for crossing restrictions (only altitude)
  CHANGELOG.md
  documentation/aircraft-commands.md
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/aircraft/AircraftModel.js
  src/assets/scripts/client/aircraft/AircraftTypeDefinitionModel.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/WaypointModel.js
  src/assets/scripts/client/aircraft/Pilot/Pilot.js
  src/assets/scripts/client/airport/AirportController.js
  src/assets/scripts/client/airport/AirportModel.js
  src/assets/scripts/client/parsers/aircraftCommandParser/aircraftCommandDefinitions.js
  src/assets/scripts/client/parsers/aircraftCommandParser/aircraftCommandMap.js
  src/assets/scripts/client/parsers/aircraftCommandParser/aircraftCommandParserMessages.js
  src/assets/scripts/client/parsers/aircraftCommandParser/argumentParsers.js
  src/assets/scripts/client/parsers/aircraftCommandParser/argumentValidators.js
  test/aircraft/AircraftModel.spec.js
  test/aircraft/AircraftTypeDefinitionModel.spec.js
  test/aircraft/FlightManagementSystem/WaypointModel.spec.js
  test/aircraft/Pilot/Pilot.spec.js
  test/parsers/aircraftCommandParser/argumentParser.spec.js
  test/parsers/aircraftCommandParser/argumentValidator.spec.js
Labels: enhancement

#1342 bugfix/1341 - fix CID number generation bug in cases of CID collision
  CHANGELOG.md
  src/assets/scripts/client/aircraft/StripView/StripViewController.js
Labels: BUGFIX

#1337 devops/598 - Add lint to travis after-success task list
  .travis.yml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: devops

#1317 enhancement/804 - add a changelog in-game
  CHANGELOG.md
  Gulpfile.js
  assets/images/icons/changelog.png
  assets/images/icons/changelog.svg
  package-lock.json
  package.json
  src/assets/scripts/client/AppController.js
  src/assets/scripts/client/changelog/ChangelogController.js
  src/assets/scripts/client/constants/selectors.js
  src/assets/scripts/client/constants/storageKeys.js
  src/assets/style/main.less
  src/assets/style/module/blackBox/_blackBox.less
  src/assets/style/module/changelog/_changelog.less
  src/index.hbs
  src/templates/_changelog.hbs
  src/templates/_footer.hbs
  tools/options.js
  tools/tasks/copyChangelog.js
Labels: enhancement

#1348 bugfix/1183 - marks a deep render on theme change
  CHANGELOG.md
  src/assets/scripts/client/canvas/CanvasController.js
Labels: BUGFIX

#1347 feature/1330 - selectable click to drag
  CHANGELOG.md
  package-lock.json
  src/assets/scripts/client/InputController.js
  src/assets/scripts/client/constants/gameOptionConstants.js
  src/assets/scripts/client/constants/inputConstants.js
  test/game/GameOptions.spec.js
Labels: feature

#1192 feature/16 - Scaling Traffic Volume
  CHANGELOG.md
  assets/images/icons/traffic.png
  assets/images/icons/traffic.svg
  src/assets/scripts/client/AppController.js
  src/assets/scripts/client/InputController.js
  src/assets/scripts/client/constants/eventNames.js
  src/assets/scripts/client/constants/selectors.js
  src/assets/scripts/client/game/GameController.js
  src/assets/scripts/client/speech.js
  src/assets/scripts/client/trafficGenerator/SpawnPatternCollection.js
  src/assets/scripts/client/trafficGenerator/SpawnPatternModel.js
  src/assets/scripts/client/trafficGenerator/SpawnScheduler.js
  src/assets/scripts/client/ui/SettingsController.js
  src/assets/scripts/client/ui/TrafficRateController.js
  src/assets/scripts/client/ui/UiController.js
  src/assets/style/main.less
  src/assets/style/module/airport/_airport.less
  src/assets/style/module/dialog/_dialog.less
  src/assets/style/module/optionDialog/_optionDialog.less
  src/templates/_airportSwitch.hbs
  src/templates/_footer.hbs
  test/fixtures/trafficGeneratorFixtures.js
  test/trafficGenerator/SpawnPatternCollection.spec.js
  test/trafficGenerator/SpawnPatternModel.spec.js
  test/trafficGenerator/SpawnScheduler.spec.js
Labels: feature
