Repository openscope/openscope, pull requests merged in 2019-01, with the labels that each got.

#1285 hotfix/1284 - fixes test
  CHANGELOG.md
  package-lock.json
  package.json
  test/aircraft/Pilot/Pilot.spec.js
  test/fixtures/aircraftFixtures.js
Labels: HOTFIX

#1282 enhancement/1247 - Initial altitude should be based on the SID
  CHANGELOG.md
  assets/airports/eddf.json
  documentation/airport-format.md
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/aircraft/AircraftModel.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/LegModel.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/RouteModel.js
  src/assets/scripts/client/navigationLibrary/ProcedureModel.js
  test/aircraft/FlightManagementSystem/Fms.spec.js
  test/aircraft/FlightManagementSystem/RouteModel.spec.js
  test/airport/_mocks/airportJsonMock.js
Labels: enhancement

#1291 documentation/1290 - Add pull reminders badge
  CHANGELOG.md
  README.md
Labels: documentation

#1287 refactor/1286 - Update EDDF to AIRAC 1901
  CHANGELOG.md
  assets/airports/eddf.json
  documentation/airport-guides/eddf.md
Labels: airport work, refactor

#1295 bugfix/1292 - Ignore taxi command during takeoff
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftModel.js
  test/aircraft/AircraftModel.spec.js
Labels: BUGFIX

#1301 devops/1288 - Update event tracking arguments
  CHANGELOG.md
  src/assets/scripts/client/EventTracker.js
  src/assets/scripts/client/constants/trackableEvents.js
  src/assets/scripts/client/ui/UiController.js
Labels: devops

#1283 feature/1234 - adds "toggle halo" command
  .eslintrc
  .gitignore
  CHANGELOG.md
  documentation/scope-commands.md
  src/assets/scripts/client/InputController.js
  src/assets/scripts/client/aircraft/AircraftConflict.js
  src/assets/scripts/client/aircraft/AircraftModel.js
  src/assets/scripts/client/canvas/CanvasController.js
  src/assets/scripts/client/constants/inputConstants.js
  src/assets/scripts/client/constants/themes/classic/modules/radarTarget.js
  src/assets/scripts/client/constants/themes/classic/modules/scope.js
  src/assets/scripts/client/constants/themes/default/color.js
  src/assets/scripts/client/constants/themes/default/modules/radarTarget.js
  src/assets/scripts/client/constants/themes/default/modules/scope.js
  src/assets/scripts/client/parsers/scopeCommandParser/ScopeCommandModel.js
  src/assets/scripts/client/parsers/scopeCommandParser/scopeCommandMap.js
  src/assets/scripts/client/scope/RadarTargetModel.js
  src/assets/scripts/client/scope/ScopeModel.js
  src/assets/scripts/client/utilities/unitConverters.js
  test/scope/RadarTargetModel.spec.js
  test/scope/ScopeModel.spec.js
Labels: feature
