Repository openscope/openscope, pull requests merged in 2019-09, with the labels that each got.

#1430 bugfix/1420 - Prespawned aircraft spawn with heading 360
  CHANGELOG.md
  src/assets/scripts/client/trafficGenerator/buildPreSpawnAircraft.js
Labels: BUGFIX

#1391 refactor/1390 - Update KAUS to AIRAC 1909
  CHANGELOG.md
  assets/airlines/baw.json
  assets/airlines/sli.json
  assets/airports/kaus.json
  documentation/airport-guides/kaus.md
Labels: airport work, refactor

#1433 bugfix/1432 - Aircraft exiting hold on their own (on develop)
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftModel.js
  src/assets/scripts/client/constants/aircraftConstants.js
  test/aircraft/AircraftModel.spec.js
Labels: BUGFIX

#1439 enhancement/1231 - Draw STAR label to the left
  CHANGELOG.md
  src/assets/scripts/client/canvas/CanvasController.js
Labels: enhancement

#1437 enhancement/1436 - Update airport maps format and render all layers
  CHANGELOG.md
  assets/airports/cyhz.json
  assets/airports/cyow.json
  assets/airports/eddf.json
  assets/airports/eddh.json
  assets/airports/eddl.json
  assets/airports/egcc.json
  assets/airports/eggw.json
  assets/airports/egnm.json
  assets/airports/engm.json
  assets/airports/kabq.json
  assets/airports/katl.json
  assets/airports/kaus.json
  assets/airports/kbos.json
  assets/airports/kcvg.json
  assets/airports/kdca.json
  assets/airports/kelp.json
  assets/airports/klas.json
  assets/airports/kmci.json
  assets/airports/kmia.json
  assets/airports/kpdx.json
  assets/airports/kpit.json
  assets/airports/krdu.json
  assets/airports/ksea.json
  assets/airports/ksfo.json
  assets/airports/kstl.json
  assets/airports/lkpr.json
  assets/airports/lrop.json
  assets/airports/lszh.json
  assets/airports/ltba.json
  assets/airports/omaa.json
  assets/airports/omdb.json
  assets/airports/othh.json
  documentation/airport-format.md
  src/assets/scripts/client/airport/AirportModel.js
  src/assets/scripts/client/airport/MapCollection.js
  src/assets/scripts/client/airport/MapModel.js
  src/assets/scripts/client/canvas/CanvasController.js
  test/airport/AirportModel.spec.js
  test/airport/MapCollection.spec.js
  test/airport/MapModel.spec.js
  test/airport/_mocks/airportJsonMock.js
  test/airport/_mocks/mapCollectionlMocks.js
  test/airport/_mocks/mapModelMocks.js
Labels: enhancement

#1441 bugfix/1440 - Add missing b738 fleet to TUI Airways (tom.json)
  CHANGELOG.md
  assets/airlines/tom.json
Labels: BUGFIX, airport work

#1435 refactor/1434 - Update EINN to AIRAC 1909
  CHANGELOG.md
  assets/airports/airportLoadList.js
  assets/airports/einn.json
  documentation/airport-guides/airport-guide-directory.md
  documentation/airport-guides/einn.md
Labels: airport work, refactor

#1445 bugfix/23 - Ensure focus is on the command input
  CHANGELOG.md
  src/assets/scripts/client/InputController.js
Labels: BUGFIX

#1442 feature/420 - Include water in terrain files
  CHANGELOG.md
  assets/airports/terrain/engm.geojson
  src/assets/scripts/client/canvas/CanvasController.js
  src/assets/scripts/client/constants/themes/classic/modules/terrain.js
  src/assets/scripts/client/constants/themes/default/modules/terrain.js
Labels: feature
