Repository openscope/openscope, pull requests merged in 2020-07, with the labels that each got.

#1611 feature/1610 - Add RJSS (Sendai Int'l)
  CHANGELOG.md
  assets/airlines/ttw.json
  assets/airports/airportLoadList.js
  assets/airports/rjss.json
  assets/airports/terrain/rjss.geojson
  documentation/airport-guides/airport-guide-directory.md
  documentation/airport-guides/rjss.md
Labels: airport work, feature

#1625 enhancement/1624 - Add speed capability to crossing restrictions
  CHANGELOG.md
  documentation/aircraft-commands.md
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/aircraft/AircraftModel.js
  src/assets/scripts/client/aircraft/FlightManagementSystem/WaypointModel.js
  src/assets/scripts/client/aircraft/Pilot/Pilot.js
  src/assets/scripts/client/parsers/aircraftCommandParser/aircraftCommandMap.js
  src/assets/scripts/client/parsers/aircraftCommandParser/aircraftCommandParserMessages.js
  src/assets/scripts/client/parsers/aircraftCommandParser/argumentParsers.js
  src/assets/scripts/client/parsers/aircraftCommandParser/argumentValidators.js
  test/parsers/aircraftCommandParser/argumentParser.spec.js
  test/parsers/aircraftCommandParser/argumentValidator.spec.js
Labels: enhancement

#1627 bugfix/1626 - Draw range rings where the file specifies instead of at the airport center
  CHANGELOG.md
  src/assets/scripts/client/airport/AirportModel.js
  src/assets/scripts/client/canvas/CanvasController.js
Labels: BUGFIX
