Repository openscope/openscope, pull requests merged in 2020-01, with the labels that each got.

#1487 refactor/1486 - AFL info updated
  CHANGELOG.md
  assets/airlines/afl.json
Labels: refactor

#1507 Fixes broken link in aircraft-commands.md
  CHANGELOG.md
  documentation/aircraft-commands.md
Labels: documentation

#1369 refactor/474 - Overhaul LOWW
  CHANGELOG.md
  assets/airlines/aca.json
  assets/airlines/ana.json
  assets/airlines/aua.json
  assets/airlines/azq.json
  assets/airlines/bcs.json
  assets/airlines/cal.json
  assets/airlines/chh.json
  assets/airlines/ctn.json
  assets/airlines/eth.json
  assets/airlines/eva.json
  assets/airlines/exs.json
  assets/airlines/ezs.json
  assets/airlines/ezy.json
  assets/airlines/fdx.json
  assets/airlines/fin.json
  assets/airlines/foo.json
  assets/airlines/klm.json
  assets/airlines/kne.json
  assets/airlines/ldm.json
  assets/airlines/lgl.json
  assets/airlines/lzb.json
  assets/airlines/pev.json
  assets/airlines/qtr.json
  assets/airlines/rja.json
  assets/airlines/rot.json
  assets/airlines/slk.json
  assets/airlines/tap.json
  assets/airlines/tay.json
  assets/airlines/tha.json
  assets/airlines/thy.json
  assets/airlines/uae.json
  assets/airlines/ups.json
  assets/airports/airportLoadList.js
  assets/airports/eham.json
  assets/airports/loww.json
  assets/airports/terrain/loww.geojson
  documentation/airport-guides/airport-guide-directory.md
  documentation/airport-guides/loww.md
Labels: airport work, refactor

#1510 refactor/1471 - Change all airport guide links to open in new tab
  CHANGELOG.md
  documentation/airport-guides/cyhz.md
  documentation/airport-guides/cyow.md
  documentation/airport-guides/eddf.md
  documentation/airport-guides/eddh.md
  documentation/airport-guides/eddl.md
  documentation/airport-guides/egcc.md
  documentation/airport-guides/eggw.md
  documentation/airport-guides/egnm.md
  documentation/airport-guides/eidw.md
  documentation/airport-guides/einn.md
  documentation/airport-guides/engm.md
  documentation/airport-guides/kabq.md
  documentation/airport-guides/katl.md
  documentation/airport-guides/kaus.md
  documentation/airport-guides/kbos.md
  documentation/airport-guides/kcvg.md
  documentation/airport-guides/kdca.md
  documentation/airport-guides/kdtw.md
  documentation/airport-guides/klas.md
  documentation/airport-guides/kmci.md
  documentation/airport-guides/kmia.md
  documentation/airport-guides/kpdx.md
  documentation/airport-guides/kpit.md
  documentation/airport-guides/krdu.md
  documentation/airport-guides/ksea.md
  documentation/airport-guides/ksfo.md
  documentation/airport-guides/kstl.md
  documentation/airport-guides/lkpr.md
  documentation/airport-guides/loww.md
  documentation/airport-guides/lrop.md
  documentation/airport-guides/ltba.md
  documentation/airport-guides/omaa.md
  documentation/airport-guides/omdb.md
  documentation/airport-guides/othh.md
Labels: refactor

#1511 bugfix/1389 - Prevent unfair penalty at KDCA on IRONS7 by deactivating R6601B/C
  CHANGELOG.md
  assets/airports/kdca.json
Labels: BUGFIX, airport work

#1512 bugfix/1218 - Ensure proper removal of aircraft who collide with terrain/traffic
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftConflict.js
  src/assets/scripts/client/aircraft/AircraftController.js
  src/assets/scripts/client/aircraft/AircraftModel.js
Labels: BUGFIX

#1516 bugfix/1513 - Add missing AFR fleets used by EDDM
  CHANGELOG.md
  assets/airlines/afr.json
  assets/airlines/ldm.json
Labels: BUGFIX, airport work

#1515 refactor/1514 - Bring back SAWH
  CHANGELOG.md
  assets/aircraft/be20.json
  assets/aircraft/be36.json
  assets/airlines/ans.json
  assets/airlines/dap.json
  assets/airlines/jes.json
  assets/airlines/lde.json
  assets/airlines/naa.json
  assets/airports/airportLoadList.js
  assets/airports/sawh.json
  assets/airports/terrain/sawh.geojson
  documentation/airport-guides/airport-guide-directory.md
  documentation/airport-guides/sawh.md
Labels: airport work, refactor

#1382 refactor/1381 - Use Jeppesen chart's english names for all airports
  CHANGELOG.md
  assets/airports/airportLoadList.js
Labels: refactor
