Repository openscope/openscope, pull requests merged in 2021-03, with the labels that each got.

#1791 refactor/1790 - Add test coverage for all command aliases
  CHANGELOG.md
  test/commands/definitions/aircraftCommandMap.spec.js
  test/commands/definitions/systemCommandMap.spec.js
  test/commands/definitions/testUtils.js
Labels: refactor

#1679 feature/1670 - Add command to get coordinates at clicked point
  CHANGELOG.md
  package-lock.json
  src/assets/scripts/client/InputController.js
  src/assets/scripts/client/airport/AirspaceModel.js
  src/assets/scripts/client/base/DynamicPositionModel.js
  src/assets/scripts/client/canvas/CanvasStageModel.js
  src/assets/scripts/client/constants/canvasConstants.js
  src/assets/scripts/client/math/vector.js
  test/base/DynamicPositionModel.spec.js
  test/canvas/CanvasStageModel.spec.js
Labels: feature

#1798 enhancement/1721 - Add labelPositions to restricted areas
  CHANGELOG.md
  documentation/airport-format.md
  src/assets/scripts/client/airport/AirportModel.js
  src/assets/scripts/client/airport/AirspaceModel.js
  src/assets/scripts/client/canvas/CanvasController.js
Labels: enhancement
