Repository openscope/openscope, pull requests merged in 2021-11, with the labels that each got.

#1850 feature/1848 - User selectable Video Maps
  CHANGELOG.md
  assets/airports/kphl.json
  src/assets/scripts/client/canvas/CanvasController.js
  src/assets/scripts/client/ui/UiController.js
  src/assets/scripts/client/ui/VideoMapController.js
  src/templates/_footer.hbs
Labels: feature

#1846 bugfix/1845 - Fix Safari browser compatibility
  CHANGELOG.md
  src/assets/scripts/client/constants/globalConstants.js
Labels: BUGFIX

#1835 refactor/1834 - Update RDU to AIRAC 2106
  CHANGELOG.md
  assets/airports/krdu.json
Labels: airport work, refactor

#1841 enhancement/1840 - Update KAUS to AIRAC 2109
  CHANGELOG.md
  assets/airlines/hal.json
  assets/airlines/jza.json
  assets/airlines/klm.json
  assets/airports/kaus.json
Labels: enhancement, airport work

#1855 feature/1854 Support configuration of spawn-time commands in SpawnPattern
  CHANGELOG.md
  assets/airports/kphl.json
  documentation/airport-guides/kphl.md
  documentation/spawnPatternReadme.md
  src/assets/scripts/client/AppController.js
  src/assets/scripts/client/InputController.js
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/aircraft/AircraftController.js
  src/assets/scripts/client/trafficGenerator/SpawnPatternModel.js
  src/assets/scripts/client/trafficGenerator/spawnPatternModelJsonValidator.js
  test/aircraft/AircraftCommander.spec.js
Labels: feature
