Repository openscope/openscope, pull requests merged in 2021-05, with the labels that each got.

#1803 enhancement/1732 - Add pronunciation to fixes in airport files
  CHANGELOG.md
  assets/airports/ksea.json
  documentation/airport-format.md
  package-lock.json
  src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js
  src/assets/scripts/client/aircraft/Pilot/Pilot.js
  src/assets/scripts/client/navigationLibrary/FixCollection.js
  src/assets/scripts/client/navigationLibrary/FixModel.js
  src/assets/scripts/client/navigationLibrary/NavigationLibrary.js
  test/aircraft/Pilot/Pilot.spec.js
  test/base/ModelSource/ModelSourceFactory.spec.js
  test/navigationLibrary/Fix/FixCollection.spec.js
  test/navigationLibrary/Fix/FixModel.spec.js
  test/navigationLibrary/NavigationLibrary.spec.js
Labels: enhancement

#1819 devops/1818 - Update lodash and dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: devops

#1823 bugfix/1820 - Update simultaneous dependent approach separation minima
  CHANGELOG.md
  src/assets/scripts/client/airport/runway/RunwayRelationshipModel.js
  test/airport/runway/RunwayRelationshipModel.spec.js
Labels: BUGFIX

#1619 feature/1593 - Add search bar in airport list
  CHANGELOG.md
  src/assets/scripts/client/InputController.js
  src/assets/scripts/client/constants/selectors.js
  src/assets/scripts/client/ui/UiController.js
  src/assets/style/module/airport/_airport.less
  src/templates/_airportSwitch.hbs
Labels: WIP, feature, help wanted
