Repository openscope/openscope, pull requests merged in 2021-01, with the labels that each got.

#1691 refactor/1684 - parser directory layout
  src/assets/scripts/client/InputController.js
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/commands/aircraftCommand/AircraftCommandModel.js
  src/assets/scripts/client/commands/aircraftCommand/aircraftCommandDefinitions.js
  src/assets/scripts/client/commands/aircraftCommand/aircraftCommandMap.js
  src/assets/scripts/client/commands/parsers/CommandParser.js
  src/assets/scripts/client/commands/parsers/argumentParsers.js
  src/assets/scripts/client/commands/parsers/argumentValidators.js
  src/assets/scripts/client/commands/parsers/parserMessages.js
  src/assets/scripts/client/commands/scopeCommand/ScopeCommandModel.js
  src/assets/scripts/client/commands/scopeCommand/scopeCommandMap.js
  src/assets/scripts/client/navigationLibrary/HoldModel.js
  test/commands/aircraftCommand/AircraftCommandModel.spec.js
  test/commands/parsers/ArgumentParsers.spec.js
  test/commands/parsers/ArgumentValidators.spec.js
  test/commands/parsers/CommandParser.spec.js
  test/commands/scopeCommand/ScopeCommandModel.spec.js
  test/scope/_mocks/scopeCommandMocks.js
Labels: refactor

#1694 bugfix/1280 - remove redundant timeout-based taxi->wait mechanism
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftModel.js
Labels: BUGFIX

#1706 bugfix/1705 - Re-fix range ring drawing position and CanvasController cleaning
  CHANGELOG.md
  assets/airports/katl.json
  assets/airports/kiad.json
  assets/airports/lkpr.json
  src/assets/scripts/client/aircraft/AircraftController.js
  src/assets/scripts/client/canvas/CanvasController.js
  src/assets/scripts/client/canvas/CanvasStageModel.js
  src/assets/scripts/client/constants/themes/default/modules/radarTarget.js
  test/canvas/CanvasStageModel.spec.js
Labels: BUGFIX

#1704 enhancement/1703 - Add PTL ranges which include 30sec
  CHANGELOG.md
  src/assets/scripts/client/constants/gameOptionConstants.js
  src/assets/scripts/client/ui/SettingsController.js
Labels: enhancement

#1698 refactor/1697 introduce parse function which returns ParsedCommand
  CHANGELOG.md
  src/assets/scripts/client/InputController.js
  src/assets/scripts/client/commands/ParsedCommand.js
  src/assets/scripts/client/commands/parsers/CommandParser.js
  test/commands/ParsedCommand.spec.js
  test/commands/parsers/CommandParser.spec.js
Labels: refactor

#1701 documentation/1699 - update+refine aircraft command documentation
  CHANGELOG.md
  documentation/aircraft-commands.md
  documentation/scope-commands.md
  src/assets/scripts/client/ui/TutorialView.js
Labels: documentation

#1723 documentation/1692 - Remove GOATZ1 and DIRBY1 caveats from KLAX airport guide
  CHANGELOG.md
  documentation/airport-guides/klax.md
Labels: documentation

#1682 refactor/1677 - Update Munich airport (EDDM)
  CHANGELOG.md
  assets/airports/eddm.json
  assets/airports/terrain/eddm.geojson
Labels: airport work, refactor

#1708 bugfix/1707 - fix various minor keyboard input bugs / UX issues
  CHANGELOG.md
  documentation/aircraft-commands.md
  src/assets/scripts/client/InputController.js
  src/assets/scripts/client/commands/aircraftCommand/aircraftCommandMap.js
Labels: BUGFIX

#1713 refactor/1712 centralize z-index declarations for ease of layer management
  CHANGELOG.md
  src/assets/style/helpers/_vars.less
  src/assets/style/landmark/_stripView.less
  src/assets/style/landmark/_tutorial.less
  src/assets/style/module/airportGuide/_airportGuide.less
  src/assets/style/module/canvas/_canvas.less
  src/assets/style/module/changelog/_changelog.less
  src/assets/style/module/controls/_controls.less
  src/assets/style/module/dialog/_dialog.less
  src/assets/style/module/info/_info.less
  src/assets/style/module/loadingView/_loadingView.less
  src/assets/style/module/log/_log.less
  src/assets/style/module/optionDialog/_optionDialog.less
  src/assets/style/module/pause/_pause.less
Labels: refactor

#1717 enhancement/1715 - Sync fast-forward menu button with timewarp system commands
  CHANGELOG.md
  documentation/aircraft-commands.md
  src/assets/scripts/client/commands/aircraftCommand/aircraftCommandMap.js
  src/assets/scripts/client/game/GameController.js
Labels: BUGFIX, enhancement

#1660 feature/1656 - Add KPHL
  CHANGELOG.md
  assets/airports/airportLoadList.js
  assets/airports/kphl.json
  assets/airports/terrain/kphl.geojson
  documentation/airport-guides/kphl.md
Labels: airport work

#1731 Refactor/1718 Sync aircraftCommandMap and aircraftCommandDefinitions
  CHANGELOG.md
  src/assets/scripts/client/commands/aircraftCommand/aircraftCommandDefinitions.js
  src/assets/scripts/client/commands/aircraftCommand/aircraftCommandMap.js
Labels: refactor

#1726 refactor/1725 - JSONize airport load list
  CHANGELOG.md
  assets/airports/airportLoadList.js
  assets/airports/airportLoadList.json
  assets/airports/airportLoadList.schema.json
  documentation/airport-format.md
  documentation/airport-load-list.md
  src/assets/scripts/client/App.js
  src/assets/scripts/client/AppController.js
  src/assets/scripts/client/airport/AirportController.js
  src/assets/scripts/client/index.js
  src/templates/layout.hbs
  tools/tasks/mediaTasks.js
Labels: refactor

#1727 enhancement/217 - differentiate color of selected aircraft path from others when projected paths set to "always"
  CHANGELOG.md
  src/assets/scripts/client/canvas/CanvasController.js
  src/assets/scripts/client/constants/themes/classic/modules/radarTarget.js
  src/assets/scripts/client/constants/themes/default/color.js
  src/assets/scripts/client/constants/themes/default/modules/radarTarget.js
Labels: enhancement
