Repository openscope/openscope, pull requests merged in 2021-02, with the labels that each got.

#1743 enhancement/495 - double click aircraft radar return scrolls strip into view
  CHANGELOG.md
  src/assets/scripts/client/InputController.js
  src/assets/scripts/client/aircraft/AircraftController.js
  src/assets/scripts/client/aircraft/StripView/StripViewController.js
  src/assets/scripts/client/aircraft/StripView/StripViewModel.js
  src/assets/scripts/client/constants/eventNames.js
Labels: enhancement

#1720 [#1719] test parse and validate properties
  CHANGELOG.md
  src/assets/scripts/client/commands/aircraftCommand/aircraftCommandDefinitions.js
  src/assets/scripts/client/commands/parsers/argumentParsers.js
  test/commands/definitions/aircraftCommandMap.spec.js
  test/commands/definitions/systemCommandMap.spec.js
  test/commands/definitions/testUtils.js
Labels: refactor

#1740 refactor/1739 - Code gardening: UiController.js
  CHANGELOG.md
  src/assets/scripts/client/ui/UiController.js
Labels: refactor

#1745 bugfix/1744 - Fix validation for "X needs to be a non-empty object"
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftTypeDefinitionModel.js
  src/assets/scripts/client/airline/AirlineModel.js
  src/assets/scripts/client/trafficGenerator/SpawnPatternCollection.js
  src/assets/scripts/client/trafficGenerator/buildPreSpawnAircraft.js
  src/assets/scripts/client/utilities/validatorUtilities.js
  test/utilities/validatorUtilities.spec.js
Labels: BUGFIX

#1710 refactor/1700 - jsonize tutorial
  CHANGELOG.md
  assets/tutorial/tutorial.json
  assets/tutorial/tutorial.schema.json
  src/assets/scripts/client/aircraft/AircraftTypeDefinitionCollection.js
  src/assets/scripts/client/aircraft/AircraftTypeDefinitionModel.js
  src/assets/scripts/client/ui/TutorialView.js
  test/aircraft/AircraftTypeDefinitionCollection.spec.js
  tools/options.js
  tools/tasks/mediaTasks.js
Labels: BUGFIX, refactor

#1748 bugfix/1690 - Clear log upon airport changed
  CHANGELOG.md
  src/assets/scripts/client/ui/UiController.js
Labels: BUGFIX

#1751 documentation/1750 - Fix syntax error in airways example
  CHANGELOG.md
  documentation/airport-format.md
Labels: documentation

#1742 enhancement/1741 - Allow one decimal in holding pattern leg length
  CHANGELOG.md
  documentation/aircraft-commands.md
  src/assets/scripts/client/constants/globalConstants.js
  test/commands/parsers/ArgumentParsers.spec.js
Labels: enhancement

#1753 devops/1752 - dependencies: install browser-env and other housekeeping
  CHANGELOG.md
  package-lock.json
  package.json
  test/aircraft/AircraftController.spec.js
  test/fixtures/scopeFixtures.js
  test/testHelpers/globalProps.js
  test/testHelpers/setupBrowserEnv.js
Labels: devops

#1759 documentation/1758 - build status badge
  CHANGELOG.md
  README.md
Labels: documentation

#1757 feature/1756 - Add Contour Airlines (VTE)
  CHANGELOG.md
  assets/airlines/BE40.json
  assets/airlines/JS31.json
  assets/airlines/JS32.json
  assets/airlines/vte.json
Labels: feature

#1766 refactor/1763 - reintegrate SQC into SIA
  CHANGELOG.md
  assets/airlines/sqc.json
  assets/airports/eham.json
  assets/airports/rjaa.json
  assets/airports/rjbb.json
  assets/airports/rksi.json
  assets/airports/vobl.json
  assets/airports/wsss.json
  assets/airports/zspd.json
Labels: airport work, refactor

#1779 refactor/1778 - StripViewModel code gardening
  CHANGELOG.md
  src/assets/scripts/client/aircraft/StripView/StripViewModel.js
Labels: refactor

#1781 refactor/1780 - implement constants for wake turbulence category & engine type
  .babelrc
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/scripts/client/aircraft/AircraftModel.js
  src/assets/scripts/client/aircraft/AircraftTypeDefinitionModel.js
  src/assets/scripts/client/constants/aircraftConstants.js
  src/assets/scripts/client/scope/RadarTargetModel.js
Labels: refactor

#1774 enhancement/1771 - Change Thomas Cook to Sunclass Airlines
  CHANGELOG.md
  assets/airlines/vkg.json
Labels: airport work, enhancement

#1613 enhancement/1417 - Add/Update RJTT (Tokyo Haneda Int'l)
  CHANGELOG.md
  assets/airlines/jal.json
  assets/airlines/jta.json
  assets/airlines/snj.json
  assets/airports/airportLoadList.json
  assets/airports/rjtt.json
  assets/airports/terrain/rjtt.geojson
  documentation/airport-guides/rjtt.md
Labels: airport work, enhancement

#1773 bugfix/1762 - defensive coding in Fms initialization
  CHANGELOG.md
  src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js
  src/assets/scripts/client/trafficGenerator/SpawnScheduler.js
  test/aircraft/FlightManagementSystem/Fms.spec.js
Labels: BUGFIX

#1784 refactor/1783 - no new AircraftTypeDefinitionModel per AircraftModel
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftModel.js
  test/aircraft/_mocks/aircraftMocks.js
Labels: refactor
