Repository openscope/openscope, pull requests merged in 2023-01, with the labels that each got.

#1788 devops/1787 - JSON schema consistency
  CHANGELOG.md
  assets/airports/airportLoadList.schema.json
  assets/autocomplete/commandAutocompleteConfig.schema.json
  assets/tutorial/tutorial.json
  assets/tutorial/tutorial.schema.json
  documentation/json-schema-standards.md
Labels: devops

#1996 refactor/1912 - Updated tutorial to reflect auto tower clearance
  CHANGELOG.md
  assets/tutorial/tutorial.json
Labels: refactor

#2023 Bugfix/2022 - "fly present heading" while still on ground
  CHANGELOG.md
  assets/autocomplete/commandAutocompleteConfig.json
  documentation/aircraft-commands.md
  src/assets/scripts/client/aircraft/AircraftCommander.js
  src/assets/scripts/client/aircraft/Pilot/Pilot.js
  test/aircraft/Pilot/Pilot.spec.js
Labels: BUGFIX

#2027 feature/2000 - Add log popup for score changes
  CHANGELOG.md
  src/assets/scripts/client/constants/selectors.js
  src/assets/scripts/client/game/GameController.js
  src/assets/style/module/controls/_controls.less
  src/assets/style/module/score/_score.less
  src/templates/_footer.hbs
Labels: feature

#2031 Enhancement/2030 - add support for system command aliases, implement 'tw' alias for 'timewarp'
  CHANGELOG.md
  assets/autocomplete/commandAutocompleteConfig.json
  documentation/aircraft-commands.md
  src/assets/scripts/client/commands/parsers/CommandParser.js
  test/commands/parsers/CommandParser.spec.js
Labels: enhancement

#2043 documentation/2042 - Update GitHub build status badge
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  documentation/airport-file-standards.md
  documentation/airport-terrain-generation.md
  src/templates/_footer.hbs
Labels: documentation

#2054 devops/2052 - Fix scripts minification
  CHANGELOG.md
  Gulpfile.js
  tools/cli.js
  tools/tasks/scriptTasks.js
Labels: devops

#2046 Refactor/2045 - assorted refactoring and optimization
  CHANGELOG.md
  src/assets/scripts/client/aircraft/AircraftController.js
  src/assets/scripts/client/aircraft/AircraftModel.js
  src/assets/scripts/client/aircraft/Pilot/Pilot.js
  src/assets/scripts/client/aircraft/StripView/StripViewController.js
  src/assets/scripts/client/airport/AirspaceModel.js
  test/aircraft/Pilot/Pilot.spec.js
Labels: refactor

#1919 refactor/1916 - Update KORD
  CHANGELOG.md
  assets/airports/airportLoadList.json
  assets/airports/kord.json
  assets/airports/terrain/kord.geojson
  documentation/airport-guides/kord.md
Labels: airport/airline/aircraft, refactor
